# -*- coding: utf-8 -*-
"""mineracao_de_dados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NxvDipAJtBJ5bPnFuSkrm3Q19xdTzGNa

#Mineração de Dados
"""

from google.colab import drive
drive.mount('/content/drive')

"""##Exemplo 1"""

import json

x = '{"nome": "Joao", "idade": 30, "cidade": "São Paulo"}'

y = json.loads(x)

print(y["nome"], y["idade"])

"""##Exemplo 2

"""

import json

data = {
    "nome": "Maria",
    "idade": 20,
    "cidade": 'Minas Gerais'
}

with open('Exemplo2.json', 'w') as file:
    json.dump(data, file)

"""##Exemplo 3"""

import json

with open('Exemplo2.json', 'r') as file:
    data = json.load(file)

data['idade'] = 56

with open('Exemplo2a.json', 'w') as file:
    json.dump(data, file)

"""##Exemplo 4

"""

import json

with open("Exemplo2.json", 'r') as file:
    data = json.load(file)

data['profissao'] = 'Engenheira'

with open('Exemplo2b.json', 'w') as file:
    json.dump(data, file)

"""##Exemplo 5

"""

import json

with open('Exemplo2c.json', 'r') as file:
    data = json.load(file)

nome = data['nome']
idade = data['idade']
profissao = data['profissao']

print(f'Nome: {nome}, Idade: {idade}, Profissão: {profissao}')

"""##Exemplo 6

"""

import json
import os

ARQUIVO = "Exemplo6.json"

if not os.path.exists(ARQUIVO):
    with open(ARQUIVO, 'w', encoding="utf-8") as f:
        json.dump([], f, indent=2, ensure_ascii=False)

with open(ARQUIVO, "r", encoding='utf-8') as f:
    data = json. load(f)

if isinstance(data, dict):
    data = [data]

data = [item for item in data if item.get("nome") !="Pedro"]

with open(ARQUIVO, 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print('Registro excluido com sucesso!')

"""##Exemplo 7"""

import json

def validar_json(json_data):
    try:
        json.loads(json_data)
        return True
    except ValueError as e:
        return False

with open('Exemplo6.json', 'r') as file:
    data = file.read()

if validar_json(data):
    print('O arquivo JSON é válido!')
else:
    print('O arquivo json é inválido')

"""##Exemplo 8

"""

import json

with open('Exemplo8.json', 'r') as arquivo:
    dados = json.load(arquivo)

indice = 0

while indice < len(dados['pessoas']):
    pessoas = dados['pessoas'][indice]
    print(f"Nome: {pessoas['nome']}")
    print(f"Idade: {pessoas['idade']}")
    print(f"Cidade: {pessoas['cidade']}")
    print("-" * 20)
    indice += 1

"""##Exemplo 9

"""

import json
import os



def ler_arquivo_json(caminho):
    with open(caminho, 'r') as arquivo:
        return json.load(arquivo)

def escrever_arquivo_json(caminho, dados):
    with open(caminho, 'w') as arquivo:
        json.dump(dados, arquivo, indent=4)

caminho_arquivo = 'Exemplo9.json'

dados = ler_arquivo_json(caminho_arquivo)

novo_nome = input("Digite o nome: ")
nova_idade = int(input("Digite a idade: "))
nova_cidade = input("Digite a cidade: ")

nova_pessoa = {
    "nome": novo_nome,
    "idade": nova_idade,
    "cidade": nova_cidade
}
dados['pessoas'].append(nova_pessoa)

escrever_arquivo_json(caminho_arquivo, dados)

print("Dados atualizados com sucesso!")

"""##Exemplo 10"""

import json

def ler_arquivo_json(caminho):
    with open(caminho, 'r') as arquivo:
        return json.load(arquivo)

def escrever_arquivo_json(caminho, dados):
    with open(caminho, 'w') as arquivo:
        json.dump(dados, arquivo, indent=4)

caminho_arquivo = "Exemplo9.json"

dados = ler_arquivo_json(caminho_arquivo)

nome_para_atualizar = input("Digite o nome da pessoa que deseja atualizar: ")

for pessoa in dados['pessoas']:
    if pessoa['nome'].lower() == nome_para_atualizar.lower():
        nova_idade = int(input(f"Digite a nova idade para {pessoa['nome']} "))
        nova_cidade = input(f"Digite a nova cidade para {pessoa['nome']} ")
        pessoa['idade'] = nova_idade
        pessoa['cidade'] = nova_cidade
        break
else:
    print("Pessoa não encontrada.")

escrever_arquivo_json(caminho_arquivo, dados)

print("Dados atualizados com sucesso!")

"""##Exemplo 11

"""

import json

def ler_arquivo_json(caminho):
    with open(caminho, 'r') as arquivo:
        return json.load(arquivo)

def escrever_arquivo_json(caminho, dados):
    with open(caminho, 'w') as arquivo:
        json.dump(dados, arquivo, indent=4)

caminho_arquivo = 'Exemplo9.json'

dados = ler_arquivo_json(caminho_arquivo)

nome_para_excluir = input("Digite o nome da pessoa que deseja excluir? ")

for pessoa in dados['pessoas']:
    if pessoa['nome'].lower() == nome_para_excluir.lower():
        dados['pessoas'].remove(pessoa)
        break
else:
    print("Pessoas não encontrada")

escrever_arquivo_json(caminho_arquivo, dados)

print("Dados atualizados com sucesso!")